### PR TITLE
Improved library management (Part1) - custom json files

### PR DESCRIPTION
**Pull request by martinmikula**
New features:
- Preferences->Arduino->Third party index url's
    - Added ability to enter custom json files also for libraries, not only for boards.
- Preferences->Arduino->Library Manager
    - Changed library selection, now json file is shown after library name (format: "library_name (json_shortname)".
Fixes:
- If package or library cannot be downloaded, proper error is shown now.... (Not cannot unpack file, but cannot download file)

### CODE REVIEW

**Comment by jantje** [comment]
That is a hell lot of change as a first pull request.
Have you run the regression tests?

**Comment by martinmikula** [comment]
It's not so big... :) It's not my first touch with java, I'm programmer for about 15years... 
About regression tests: no, i missed tests in the code completely, but I will take a look... 
It's part 1 because this patch adds ability to manage also external libraries (not from arduino itself) but this leads into a lot of situation which need to be solved or taken into account.
For example: if you have two different libs from two different vendors but with the same name - it will produce a conflict... They are shown in the manager as two different libraries, but in actual situation you can install only one of them.... 
My final vision is to have three identifications for json managed libraries (provider, name, version) to be able to install different versions from different providers at the same time (some project may need older version, some need newer version). This will need to extend add library to project dialog... 
I already have a vision in my head, but this first part is usable and it's only managing part... The other parts will probably go deeper and for me it's better to integrate smaller parts than one really big...

**Comment by martinmikula** [comment]
Changes in short (most are done in three files):

- Manager: here I change library index to list of indexes... and also loading mechanism is changed, in original version, there was two different methods used for loading library json and for loading package json... Now only one method exists: loadJsons which load all defined json files and decide by name if its board or library... and add it into right index list...

- LibraryManager: most of the work is done here, all changes are needed because of change from one library json file to multiple...

- LibrarySelectionPage: it looks like I rewrite whole method createTree, but I changed only two lines - probably we have different formating settings (i have eclipse default), but it reformat the method completely... another change in this file is only for change visible text from "library_name" to "library_name (provider)"

- a lot of other changes are really cosmetical... In old code there was two different names used for json files, boards, packages -> i replaced them with "json", because now it can be package or library. (when i'm looking to the patch some methods still need to be renamed... )

- because of formatting change in LibrarySelectionPage file i think we really should synchronize our code style (especially tab width and spaces/tabs behavior)

**Comment by jantje** [comment]
>It's not so big... :) It's not my first touch with java, I'm programmer for about 15years...

I never said it was big for you :-). I said it was big for a first pull request. Basically to big for me to get the changes based on the code and feel comfortable to accept the pull request. After all there is no basis for me to "judge the pull request" except for the code since this comes all out of the blue. A nice present though as I have been thinking about adding multiple library json files but never got to it :-))

>For example: if you have two different libs from two different vendors but with the same name - it will produce a conflict... They are shown in the manager as two different libraries, but in actual situation you can install only one of them....

This problem already exists with private libraries and the "official libraries". The current algorithm prefers private libraries before "official libraries" and private libraries are preferred in order of the list of private library locations. (I'm not sure whether I start from the top or the bottom but this hasn't happened often yet)
I feel your change expands the official libraries (as this is a json file) so we could stay with the same algorithm having a sort in the json files like the private libraries.
Note that this algorithm does not allow for using 2 different libraries with the same name as always the same library is chosen by Sloeber.
I think this is not a problem because you will always have a "preferred one" and a "special one". To use the special one you can use the "add code to the project wizard"

>My final vision is to have three identifications for json managed libraries (provider, name, version) to be able to install different versions from different providers at the same time (some project may need older version, some need newer version). This will need to extend add library to project dialog...

As you may have understood from the explanation above I don't think this is a good idea.
My main concern here is the "automatically adding libraries" feature. This feature makes that adding a #include directive in the code makes Sloeber to search for the library to add and then adds it. 
This is a Arduino IDE used feature with which I want to stay compatible to have the examples working out of the box.

>because of formatting change in LibrarySelectionPage file i think we really should synchronize our code style (especially tab width and spaces/tabs behavior)

There have been quite some discussions about this in the past and we agreed to use the "Eclipse [built-in]" style. I have the settings to format the file on saving. Still I see some "unexpected changes" from time to time.
I see LibrarySelectionPage was still "badly formatted" so I checked the file in properly formatted. If you update the pull request your changes should be visible:-)

From the read.me 
> To avoid having changes all the time because of different formatting this project uses the standard "Eclipse [built-in]".
> 
> Go to
> 
>     Window → Preferences → Java → Code Style → Formatter
> 
> and check this setting.

>About regression tests: no, i missed tests in the code completely, but I will take a look...

The regression tests are in io.sloeber.core/scr/junit.
Running the create and compile will install all json package files I have grabbed of https://github.com/arduino/Arduino/wiki/Unofficial-list-of-3rd-party-boards-support-urls
The first time it takes really long to get started because of the downloads and so. The run takes long as well as about 500 projects will be created and build.

Create and compile examples will create a project for each and every installed example and compile it. You should really extend this to add at least two json files which both installs at least 1 library containing examples.
But this can be done in a different pull request.

**Comment by jantje** [comment]
@martinmikula 
Can you update the pull request so I have a better view on the changes in LibrarySelectionPage.java

I would like to accept this pull request as some other work needs to be done

**Comment by martinmikula** [comment]
Hi, sorry for late answer, I updated merge request. Only a small reaction to your previous post: I also want to maintain compatibility with arduino... I only want to add possibility to install multiple versions of library. But there will be a "update" in auto lib selection, that latest version of lib will be automatically selected. But we can discuss this theme in proper time, when i will have something usable, something that you can try and say your feedback... :)

**Comment by jantje** [comment]
>something that you can try and say your feedback... :)

ok :-)

**Pull request merged**
