### PR TITLE
Product maintenance #1252

### PR DESCRIPTION
**Pull request by wimjongman**
Fixed some old update sites

### CODE REVIEW

**Comment by jantje** [comment]
I restarted the test as I'm unsure why it failed

**Comment by jantje** [comment]
build failed again in master. Wondering this is related to this change or some travis issue.
Anyway I restarted the travis build on master

**Comment by wimjongman** [comment]
I restarted the PR build and it was successful.. It also builds locally.

**Comment by jantje** [comment]
travis is fine now as well. I guess it is a travis issue.

**Pull request merged**
