### PR TITLE
Java11 compatible

### PR DESCRIPTION
**Pull request by wimjongman**
Move all plugins to java 11

### CODE REVIEW

**Comment by jantje** [comment]
I think this pull request is ready to pull.
Can you change the status from draft to ready?

**Comment by wimjongman** [comment]
Early start? 🌞

**Comment by jantje** [comment]
Nope: bed time story ;-)

**Comment by jantje** [comment]
There is a problem with this pull request.
When you try to run the product in java11 you will get the error
`Caused by: java.lang.UnsupportedClassVersionError: io/sloeber/core/toolchain/ArduinoLanguageProvider has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0`
I have been trying for a couple of days to fix this but I failed. so I went back to this branch and I noticed the same issue here.
I tried to fix here and it worked.
I'm bafflegasted but happy that it works so I will create a new pull request.
This is my workspace compiler setting
afbeelding

[java11errorlog.log](https://github.com/Sloeber/arduino-eclipse-plugin/files/10096439/java11errorlog.log)

**Comment by jantje** [comment]
I tried to push the changes and now I get
afbeelding
He complains about the actions but I didn't touch those :-(

afbeelding

**Comment by jantje** [comment]
So I switched back to the branch I was working on and now it works :-S

**Pull request merged**
