### PR TITLE
parallel build by default in new project

### PR DESCRIPTION
**Pull request by bergmannm**
Enable parallel build by default in new projects, that should make builds quite a bit faster.

### CODE REVIEW

**Comment by jantje** [comment]
Personally I don't want parallel builds on by default as the output of the build becomes unreadable.
But I don't object a option to set this on or off.

**Comment by bergmannm** [comment]
I don't have much experience with eclipse plugin development, so I've tried to keep the style of surrounding code.

**Comment by wimjongman** [comment]
@bergmannm you know you can build and test locally, right.

**Comment by bergmannm** [comment]
@wimjongman I've ran the tests (mvn clean verify -Dtest=RegressionTest) and they finished succesfully. If you look at previous commits in master, Travis CI build is failing for them as well.

**Comment by jantje** [comment]
The failing build has something to do with a package that fails to download.
It has nothing to do with your change. The test runs fine here and on my build server so I guess it is a security related thing

**Pull request merged**
