### PR TITLE
upgrade to 4,4,3

### PR DESCRIPTION
**Pull request by jantje**
Still work in progress

### CODE REVIEW

**Comment by jantje** [comment]
@wimjongman 
Hi Wim; 
I'm trying to make a new release but I fail to get the products to load (no splash no icons)
I've been looking at this issue for some days now but still have no clue why the maven build starts without the splash
Would you be willing to take a look at this branch if you had some time?
Thanks
Jantje

**Comment by jantje** [comment]
@wimjongman 
I think I found the issue.

**Comment by jantje** [comment]
@wimjongman 
Here is what I found: https://github.com/eclipse-tycho/tycho/issues/3433#issuecomment-1922340112
I'm thinking about when we talked about the fact I removed the application plugin.

**Comment by wimjongman** [comment]
Great! Sorry for the late response, I am swamped with work.

**Comment by jantje** [comment]
@wimjongman 
Don't be sorry. I'm grateful for your help.
In this case just calling in the cavalry was enough to win the battle.
Make sure you take enough "me time".

**Pull request merged**
